app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
    path('', include('authentication.urls')),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('products/list/', views.ProductListView.as_view(), name='products_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/detail/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
]

inflows/models.py
from django.db import models
from django.contrib.auth.models import User

from suppliers.models import Supplier


class Inflow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='inflows')
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, related_name='inflows')
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name='inflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Preço de custo no momento da entrada de produtos
    selling_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Preço de venda no momento da entrada de produtos
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

products/models.py
from django.db import models
from django.contrib.auth.models import User

from brands.models import Brand
from inflows.models import Inflow
from categories.models import Category


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='products')
    title = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    serie_number = models.CharField(max_length=200, null=True, blank=True)
    cost_price = models.DecimalField(max_digits=20, decimal_places=2)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['title']

    def __str__(self):
        return self.title

    @property
    def quantity(self):
        inflows = Inflow.objects.filter(product=self).aggregate(
            total_quantity=models.Sum('quantity')
        )
        return inflows['total_quantity'] or 0

products/forms.py
from django import forms

from brands.models import Brand
from categories.models import Category
from . import models


class ProductForm(forms.ModelForm):

    class Meta:
        model = models.Product
        fields = ['title', 'category', 'brand', 'description', 'serie_number', 'cost_price', 'selling_price']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'},),
            'brand': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'serie_number': forms.TextInput(attrs={'class': 'form-control'}),
            'cost_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'selling_price': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Título',
            'category': 'Categoria',
            'brand': 'Marca',
            'description': 'Descrição',
            'serie_number': 'Número de Série',
            'cost_price': 'Preço de Custo',
            'selling_price': 'Preço de Venda',
        }

    def __init__(self, *args, user=None, **kwargs):
        """Filtra as categorias e marcas com base no usuário logado"""
        super().__init__(*args, **kwargs)

        if user:
            self.fields['category'].queryset = Category.objects.filter(user=user)
            self.fields['brand'].queryset = Brand.objects.filter(user=user)
        else:
            self.fields['category'].queryset = Category.objects.none()
            self.fields['brand'].queryset = Brand.objects.none()

products/views.py
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from brands.models import Brand
from categories.models import Category
from utils.metrics import get_products_metrics
from .models import Product
from .forms import ProductForm


class ProductListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Product
    template_name = 'products/products_list.html'
    context_object_name = 'products'
    paginate_by = 10
    permission_required = 'products.view_product'

    def get_queryset(self):
        queryset = Product.objects.select_related('category', 'brand').all().filter(user=self.request.user)

        title = self.request.GET.get('title')
        serie_number = self.request.GET.get('serie_number')
        category = self.request.GET.get('category')
        brand = self.request.GET.get('brand')

        filters = {}

        if title:
            filters['title__icontains'] = title
        if serie_number:
            filters['serie_number__icontains'] = serie_number
        if category:
            filters['category__id'] = category
        if brand:
            filters['brand__id'] = brand

        if filters:
            queryset = queryset.filter(**filters)

        return queryset.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        context['page_product_is_active'] = 'active'
        context['products_metrics'] = get_products_metrics(user=self.request.user)
        return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'products/product_create.html'
    form_class = ProductForm
    success_url = reverse_lazy('products:products_list')
    permission_required = 'products.add_product'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(user=self.request.user, **self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_product_is_active'] = 'active'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'
    permission_required = 'products.view_product'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_product_is_active'] = 'active'
        return context


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    template_name = 'products/product_update.html'
    form_class = ProductForm
    success_url = reverse_lazy('products:products_list')
    permission_required = 'products.change_product'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(user=self.request.user, **self.get_form_kwargs())

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_product_is_active'] = 'active'
        return context


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'products/product_delete.html'
    success_url = reverse_lazy('products:products_list')
    permission_required = 'products.delete_product'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_product_is_active'] = 'active'
        return context

products/templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h3 class="display-4">Cadastrar Produto</h3>

  <div class="card">
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar Produto</button>
      </form>
    </div>
  </div>
  <a href="{% url 'products:products_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de
    Produtos</a>
</div>
{% endblock %}

products/templates/products/product_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h3 class="display-4">Deletar Produto</h3>

  <div class="card">
    <div class="card-body">
      <p class="card-text">Tem certeza de que deseja excluir o produto <strong>{{ object.title }}</strong>?</p>

      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Deletar</button>
      </form>

      <a href="{% url 'products:products_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de
        Produtos</a>
    </div>
  </div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h3 class="display-4">Detalhes do Produto</h3>

  <div class="card">
    <div class="card-body">
      <h3 class="card-title">{{ object.title }}</h3>
      <p class="card-text">Categoria: {{ object.category }}</p>
      <p class="card-text">Marca: {{ object.brand }}</p>
      <p class="card-text">{{ object.description }}</p>
      <p class="card-text">Número de Série: <strong>{{ object.serie_number }}</strong></p>
      <p class="card-text">Preço de Custo: <strong>R$ {{ object.cost_price }}</strong></p>
      <p class="card-text">Preço de Venda: <strong>R$ {{ object.selling_price }}</strong></p>
      <p class="card-text">Quantidade em Estoque: <strong>{{ object.quantity }}</strong></p>
    </div>
  </div>

  <a href="{% url 'products:products_list' %}" class="btn btn-secondary mt-3">Voltar para a Lista de Produtos</a>
</div>
{% endblock %}

products/templates/products/product_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h3 class="display-4">Editar Produto</h3>

  <div class="card">
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar Produto</button>
      </form>
    </div>
  </div>

  <a href="{% url 'products:products_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de
    Produtos</a>
</div>
{% endblock %}

products/templates/products/products_list.html
{% extends 'base.html' %}

{% block title %}
SGE - Produtos
{% endblock %}

{% block content %}

{% if perms.products.view_product and perms.inflows.view_inflow %}
{% include 'components/_products_metrics.html' %}
{% endif %}

<div class="mb-4"></div>

<div class="row mb-3">
  <div class="col-md-6 mb-md-0">
    <form method="get" action="{% url 'products:products_list' %}">
      <div class="input-group">
        <input type="text" class="form-control" name="title" placeholder="Título" value="{{ request.GET.title }}">
        <input type="text" class="form-control" name="serie_number" placeholder="Número de Série"
          value="{{ request.GET.serie_number }}">
        <button type="submit" class="btn btn-primary">
          <i class="bi bi-search"></i>
        </button>
      </div>
    </form>
  </div>

  {% if perms.products.add_product %}
  <div class="col-md-6">
    <a href="{% url 'products:product_create' %}" class="btn btn-success float-end mt-3 mt-sm-0">
      <i class="bi bi-plus"></i> Novo Produto
    </a>
  </div>
  {% endif %}

</div>

<div class="row mb-3">
  <div class="col-md-6">
    <form method="get" action="{% url 'products:products_list' %}">
      <div class="input-group">
        <select class="form-select" name="category">
          <option value="" {% if not request.GET.category %} selected {% endif %}>Todas as Categorias</option>
          {% for category in categories %}
            <option value="{{ category.id }}" {% if request.GET.category|default:"" == category.id|stringformat:"s" %} selected {% endif %}>{{ category.name }}</option>
          {% endfor %}
        </select>
        <select class="form-select" name="brand">
          <option value="" {% if not request.GET.brand %} selected {% endif %}>Todas as Marcas</option>
          {% for brand in brands %}
          <option value="{{ brand.id }}" {% if request.GET.brand|default:"" == brand.id|stringformat:"s" %} selected {% endif %}>{{ brand.name }}
          </option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary">
          <i class="bi bi-filter"></i> Filtrar
        </button>
      </div>
    </form>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="d-none d-lg-table-cell">ID</th>
        <th>Título</th>
        <th>Categoria</th>
        <th>Marca</th>
        <th>Preço de Custo</th>
        <th>Preço de Venda</th>
        <th class="d-none d-lg-table-cell">Número de Série</th>
        <th>Quantidade</th>
        <th class="d-none d-sm-table-cell">Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr>
        <td class="d-none d-lg-table-cell">
          <a href="{% url 'products:product_detail' product.id %}" class="text-primary fw-semibold">
            {{ product.id }}
          </a>
        </td>
        <td>{{ product.title }}</td>
        <td>{{ product.category }}</td>
        <td>{{ product.brand }}</td>
        <td>R$ {{ product.cost_price }}</td>
        <td>R$ {{ product.selling_price }}</td>
        <td class="d-none d-lg-table-cell">{{ product.serie_number|default:'Não informado' }}</td>
        <td>{{ product.quantity }}</td>
        <td class="d-flex flex-wrap gap-1 d-none d-sm-table-cell text-center">
          <a href="{% url 'products:product_detail' product.id %}" class="btn btn-info btn-sm">
            <i class="bi bi-eye"></i>
          </a>

          {% if perms.products.change_product %}
          <a href="{% url 'products:product_update' product.id %}" class="btn btn-warning btn-sm">
            <i class="bi bi-pencil"></i>
          </a>
          {% endif %}

          {% if perms.products.delete_product %}
          <a href="{% url 'products:product_delete' product.id %}" class="btn btn-danger btn-sm btn-delete">
            <i class="bi bi-trash"></i>
          </a>
          {% endif %}

        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>  
</div>

{% include 'components/_pagination.html' %}

{% endblock %}